/**
 * Auto Design Service
 * Automatically generates Polotno designs from AI specs and Ideogram images
 */

import { generateDesign, DesignSpecs } from './designGenerator';

export interface Post {
  id: string;
  title: string;
  content: string;
  design_specs?: any;
  design_thumbnail?: string;
}

/**
 * Convert AI design specs to Polotno design specs
 */
function convertAISpecsToPolotnoSpecs(
  post: Post,
  backgroundImageUrl?: string
): DesignSpecs {
  const aiSpecs = post.design_specs || {};
  
  // Map AI position to pixel coordinates (for 1080x1080 canvas)
  const positionMap = {
    top: { title: 150, content: 800 },
    center: { title: 400, content: 600 },
    bottom: { title: 700, content: 900 },
  };
  
  const titlePos = aiSpecs.title_position || 'center';
  const contentPos = aiSpecs.content_position || 'center';
  const positions = positionMap[titlePos as keyof typeof positionMap] || positionMap.center;
  
  // Truncate content for better display
  const contentText = post.content.length > 200 
    ? post.content.substring(0, 197) + '...' 
    : post.content;
  
  return {
    backgroundImage: backgroundImageUrl || post.design_thumbnail,
    backgroundColor: aiSpecs.primary_color || '#6366f1',
    overlayColor: aiSpecs.overlay_color || '#000000',
    overlayOpacity: aiSpecs.overlay_opacity || 0.3,
    title: {
      text: post.title,
      x: 50,
      y: positions.title,
      fontSize: aiSpecs.title_size || 72,
      color: '#FFFFFF',
      fontFamily: 'Roboto',
      align: 'center',
    },
    content: {
      text: contentText,
      x: 50,
      y: positions.content,
      fontSize: aiSpecs.content_size || 36,
      color: '#FFFFFF',
      fontFamily: 'Roboto',
      align: 'center',
    },
    shapes: [
      {
        type: 'rect',
        x: 50,
        y: positions.title - 20,
        width: 120,
        height: 8,
        fill: aiSpecs.accent_color || '#fbbf24',
        opacity: 1,
      },
    ],
  };
}

/**
 * Automatically generate a design for a post
 */
export async function autoGenerateDesign(post: Post): Promise<string> {
  try {
    console.log('🎨 Auto-generating design for post:', post.id);
    
    // Convert AI specs to Polotno specs
    const designSpecs = convertAISpecsToPolotnoSpecs(post);
    
    // Generate design programmatically
    const designDataURL = await generateDesign(designSpecs, { format: 'square' });
    
    console.log('✅ Design generated successfully');
    return designDataURL;
    
  } catch (error) {
    console.error('❌ Failed to auto-generate design:', error);
    throw error;
  }
}

/**
 * Batch generate designs for multiple posts
 */
export async function batchGenerateDesigns(posts: Post[]): Promise<Map<string, string>> {
  const results = new Map<string, string>();
  
  for (const post of posts) {
    try {
      const designURL = await autoGenerateDesign(post);
      results.set(post.id, designURL);
    } catch (error) {
      console.error(`Failed to generate design for post ${post.id}:`, error);
      // Continue with other posts
    }
  }
  
  return results;
}

/**
 * Upload generated design to backend
 */
export async function uploadGeneratedDesign(
  postId: string,
  designDataURL: string
): Promise<void> {
  try {
    // Convert data URL to Blob
    const response = await fetch(designDataURL);
    const blob = await response.blob();
    
    // Create FormData
    const formData = new FormData();
    formData.append('image', blob, `design_${postId}.png`);
    
    // Upload to backend
    const uploadResponse = await fetch(
      `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/posts/${postId}/upload-image/`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${localStorage.getItem('access_token')}`,
        },
        body: formData,
      }
    );
    
    if (!uploadResponse.ok) {
      throw new Error('Failed to upload design to backend');
    }
    
    console.log('✅ Design uploaded to backend');
    
  } catch (error) {
    console.error('❌ Failed to upload design:', error);
    throw error;
  }
}


